name: lints

on:
  push:
    branches: [main]
    tags:
  pull_request:
  workflow_dispatch:

jobs:
  lints:
    timeout-minutes: 10

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cargo Format
        run: cargo fmt --check

      - name: Cargo Clippy
        run: cargo clippy -- -D warnings
