name: tests

on:
  push:
    branches: [main]
    tags:
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    timeout-minutes: 10

    strategy:
      matrix:
        include:
        - os: ubuntu-latest
          python: '3.9'
          toxenv: py39
        - os: ubuntu-latest
          python: '3.10'
          toxenv: py310
        - os: ubuntu-latest
          python: '3.11'
          toxenv: py311
        - os: ubuntu-latest
          python: '3.12'
          toxenv: py312
        - os: ubuntu-latest
          python: '3.13'
          toxenv: py313
        - os: macos-13
          python: '3.9'
          toxenv: py39
        - os: macos-13
          python: '3.10'
          toxenv: py310
        - os: macos-14
          python: '3.11'
          toxenv: py311
        - os: macos-14
          python: '3.12'
          toxenv: py312
        - os: macos-13
          python: '3.13'
          toxenv: py313
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install Package
        run: pip install .[dev]

      - name: Run PyTest
        run: pytest
